In [251]:
import tensorflow  as tf

In [252]:
from tensorflow import keras

In [253]:
import pandas as pd

In [254]:
import numpy as np

In [255]:
#importating the data set
weather_dataset = pd.read_csv('5 day forcast.csv')

In [256]:
print(weather_dataset)

        Day   Time  entry_id  Temperature  Humidity  UV_level  Rain  \
0       San  60000         1         31.2      87.1        22     1   
1       San  60020         2         31.2      87.3        23     1   
2       San  60040         3         31.2      87.3        32     1   
3       San  60100         4         31.2      87.2       322     1   
4       San  60120         5         31.2      87.0        33     1   
...     ...    ...       ...          ...       ...       ...   ...   
21596  Thur  55820     21597         30.8      86.5         0     0   
21597  Thur  55840     21598         30.8      86.5         0     0   
21598  Thur  55900     21599         30.8      86.5         0     0   
21599  Thur  55920     21600         30.8      86.6         0     0   
21600  Thur  55940     21601         30.9      87.0         0     0   

       Wind_Speed  
0            0.00  
1            0.00  
2            0.00  
3            0.00  
4            2.85  
...           ...  
21596  

In [257]:
#shuffling the data
np.random.shuffle(weather_dataset.values)

In [258]:
print(weather_dataset.values)

[['San' 60000 1 ... 22 1 0.0]
 ['San' 60020 2 ... 23 1 0.0]
 ['San' 60040 3 ... 32 1 0.0]
 ...
 ['Thur' 55900 21599 ... 0 0 4.43]
 ['Thur' 55920 21600 ... 0 0 4.87]
 ['Thur' 55940 21601 ... 0 0 3.67]]


In [259]:
#convertion of the date field in to integer format
day_dic = {
    'San': 1,
    'Man': 2,
    'Tues': 3,
    'Wedn': 4,
    'Thur': 5
}

In [260]:
print(day_dic)

{'San': 1, 'Man': 2, 'Tues': 3, 'Wedn': 4, 'Thur': 5}


In [261]:
weather_dataset['Day'] = weather_dataset.Day.apply(lambda x:day_dic[x])

In [262]:
print(weather_dataset['Day'] )

0        1
1        1
2        1
3        1
4        1
        ..
21596    5
21597    5
21598    5
21599    5
21600    5
Name: Day, Length: 21601, dtype: int64


In [263]:
# Formulating inputs
weather_inputs = np.column_stack((weather_dataset.Day.values,weather_dataset.Time.values,weather_dataset.Temperature.values,weather_dataset.Humidity.values,weather_dataset.UV_level.values))


In [264]:
print(weather_inputs)

[[1.000e+00 6.000e+04 3.120e+01 8.710e+01 2.200e+01]
 [1.000e+00 6.002e+04 3.120e+01 8.730e+01 2.300e+01]
 [1.000e+00 6.004e+04 3.120e+01 8.730e+01 3.200e+01]
 ...
 [5.000e+00 5.590e+04 3.080e+01 8.650e+01 0.000e+00]
 [5.000e+00 5.592e+04 3.080e+01 8.660e+01 0.000e+00]
 [5.000e+00 5.594e+04 3.090e+01 8.700e+01 0.000e+00]]


In [265]:
#formulating outputs
weather_outputs = np.column_stack((weather_dataset.Rain.values,weather_dataset.Wind_Speed.values))


In [266]:
print(weather_outputs)

[[1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]
 ...
 [0.   4.43]
 [0.   4.87]
 [0.   3.67]]


In [267]:
print()
print('Building the nurel engine')


Building the nurel engine


In [268]:
#preparing the nureal engine
weather_NN = keras.Sequential([
    keras.layers.Dense(128, input_shape=(5,), activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(4, activation='relu'),
    keras.layers.Dense(2, activation='sigmoid')
])

In [269]:
#compiling the engine
weather_NN.compile(optimizer='adam', loss=keras.losses.CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])


In [283]:
weather_NN.fit(weather_inputs.astype(np.float32), weather_outputs.astype(np.float32), batch_size=4, epochs=10)


Epoch 1/10
5401/5401 [==============================] - 31s 6ms/step - loss: 4.4363 - accuracy: 0.8772
Epoch 2/10
5401/5401 [==============================] - 29s 5ms/step - loss: 4.4695 - accuracy: 0.8772
Epoch 3/10
5401/5401 [==============================] - 29s 5ms/step - loss: 4.5000 - accuracy: 0.8772
Epoch 4/10
5401/5401 [==============================] - 36s 7ms/step - loss: 4.5335 - accuracy: 0.8772
Epoch 5/10
5401/5401 [==============================] - 36s 7ms/step - loss: 4.5732 - accuracy: 0.8772
Epoch 6/10
5401/5401 [==============================] - 33s 6ms/step - loss: 4.6118 - accuracy: 0.8772
Epoch 7/10
5401/5401 [==============================] - 40s 7ms/step - loss: 4.6491 - accuracy: 0.8772
Epoch 8/10
5401/5401 [==============================] - 35s 7ms/step - loss: 4.6927 - accuracy: 0.8772
Epoch 9/10
5401/5401 [==============================] - 32s 6ms/step - loss: 4.7314 - accuracy: 0.8772
Epoch 10/10
5401/5401 [==============================] - 32s 6ms/step - l

In [282]:
print('prediction',weather_NN.predict(np.column_stack((4,220020,30.7,93.7,0))))

1/1 [==============================] - 0s 77ms/step
prediction [[1. 1.]]


In [276]:
import numpy as np

# Input data for prediction
input_data = np.array([[3, 121200, 30.7, 86.7, 40]], dtype=np.float32)

# Get the predicted output
prediction = weather_NN.predict(input_data)

# Define the actual output value
actual_output =  np.array([[1,1]], dtype=np.float32)

# Compare the predicted output with the actual output
accuracy = np.mean(np.equal(prediction, actual_output))

print('Accuracy:', accuracy)


1/1 [==============================] - 0s 44ms/step
Accuracy: 1.0
